#!/bin/bash

# JSON object to pass to Lambda Function
json={"\"name\"":"\"Susan\u0020Smith\",\"param1\"":1,\"param2\"":2,\"param3\"":3}

#echo "Invoking Lambda function using API Gateway"
#time output=`curl -s -H "Content-Type: application/json" -X POST -d $json  https://4fom2mh7tk.execute-api.us-east-2.amazonaws.com/helloMySql_dev`
#echo ""

#echo ""
#echo "JSON RESULT:"
#echo $output | jq
#echo ""



#TODO: modify callservice.sh to invoke helloMySql to write names to specified db.properties file (database=TEST, table=mytable)
	#then in cmd: time ./callservice.sh

#json={"\"name\"":"\"$1\u0020$2\",\"param1\"":1,\"param2\"":2,\"param3\"":3} #$1 = 1st arg, $2 = 2nd arg

echo "Invoking Lambda function using AWS CLI"
time output=`aws lambda invoke --invocation-type RequestResponse --function-name helloMySql --region us-east-2 --payload $json /dev/stdout | head -n 1 | head -c -2 ; echo`

echo ""
echo "JSON RESULT:"
echo $output | jq
echo $output | jq > db.properties
echo ""
